# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['LUDOMANAGER_DEV_DATABASE'] %>
  host: <%= ENV['LUDOMANAGER_DEV_HOST'] %>
  port: <%= ENV['LUDOMANAGER_DEV_PORT'] %>
  username: <%= ENV['LUDOMANAGER_DEV_USER'] %>
  password: <%= ENV['LUDOMANAGER_DEV_PASSWORD'] %>
  pool: 5
  timeout: 5000
